-- products: the 80 foods FreshFeed gives advice for.
--
-- Built from the Produce Cold Storage & Postharvest Handling Technical Manual
-- (docs/produce-cold-storage-manual.pdf), with respiration rates from USDA Agriculture
-- Handbook 66 (2016) and storage life from Cantwell, UC Davis (2001).
--
--   fresh_produce  (§1)  storage group, temperature, RH, ethylene role, chilling sensitivity,
--                         respiration class and rates (mg CO2/kg·h at 0–25°C), storage life
--   dairy          (§2)  moisture, fat, pH, failure mode, storage protocol
--   bakery_snack   (§3)  moisture, fat, water activity, failure mode, packaging need
--   fermented      (§4)  pH, salt brine, chilled storage protocol
--   dried_produce        nuts, dates, dried fruit and vegetables (very low respiration)
--
-- Names are in English, Hindi and Marathi. respiration_estimated = true marks rows
-- where the class is an estimate (explained in respiration_source).
-- Public read-only.

create table if not exists public.products (
  id                     serial primary key,
  name                   text not null unique,
  hindi_name             text,
  gujarati_name          text,
  commodity_class        text not null
                         check (commodity_class in ('fresh_produce','dried_produce','dairy','bakery_snack','fermented')),
  category               text,
  storage_group_id       smallint references public.storage_groups (id),
  moisture_min           numeric,
  moisture_max           numeric,
  fat_min                numeric,
  fat_max                numeric,
  ph_min                 numeric,
  ph_max                 numeric,
  aw_min                 numeric,
  aw_max                 numeric,
  salt_min               numeric,
  salt_max               numeric,
  storage_temp_c_min     numeric,
  storage_temp_c_max     numeric,
  rh_min                 numeric,
  rh_max                 numeric,
  ethylene_role          text check (ethylene_role in ('producer','sensitive','producer_and_sensitive') or ethylene_role is null),
  chilling_sensitive     boolean,
  respiration_class      text check (respiration_class in ('very_low','low','moderate','high','very_high','extremely_high') or respiration_class is null),
  precooling_method      text,
  primary_failure        text,
  packaging_note         text,
  storage_protocol       text,
  shelf_life_note        text,
  data_notes             text,
  source                 text default 'Produce Cold Storage & Postharvest Handling Technical Manual',
  resp_rate_min          numeric,
  resp_rate_max          numeric,
  resp_rate_temp_c       numeric,
  resp_mg_0c             numeric,
  resp_mg_5c             numeric,
  resp_mg_10c            numeric,
  resp_mg_15c            numeric,
  resp_mg_20c            numeric,
  resp_mg_25c            numeric,
  respiration_source     text,
  respiration_estimated  boolean not null default false,
  marathi_name           text,
  storage_life_text      text,
  storage_life_min_days  integer,
  storage_life_max_days  integer,
  storage_life_source    text
);

create index if not exists products_storage_group_id_idx on public.products (storage_group_id);

alter table public.products enable row level security;

drop policy if exists "Public read products" on public.products;
create policy "Public read products" on public.products
  for select using (true);

insert into public.products (id, name, hindi_name, gujarati_name, commodity_class, category, storage_group_id, moisture_min, moisture_max, fat_min, fat_max, ph_min, ph_max, aw_min, aw_max, salt_min, salt_max, storage_temp_c_min, storage_temp_c_max, rh_min, rh_max, ethylene_role, chilling_sensitive, respiration_class, precooling_method, primary_failure, packaging_note, storage_protocol, shelf_life_note, data_notes, source, resp_rate_min, resp_rate_max, resp_rate_temp_c, resp_mg_0c, resp_mg_5c, resp_mg_10c, resp_mg_15c, resp_mg_20c, resp_mg_25c, respiration_source, respiration_estimated, marathi_name, storage_life_text, storage_life_min_days, storage_life_max_days, storage_life_source) values
  (1, 'Apples', 'सेब', NULL, 'fresh_produce', 'fruit', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '2', '90', '95', 'producer', 'false', 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Produce Cold Storage & Postharvest Handling Technical Manual', '3', '8', '0', '3', '6', '9', '15', '20', NULL, 'Class: user-supplied respiration data. Rates: USDA Agriculture Handbook 66 (2016), Table 1 — Fall apples', 'false', 'सफरचंद', '3–6 months', '90', '180', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (2, 'Pears', 'नाशपाती', NULL, 'fresh_produce', 'fruit', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '2', '90', '95', 'producer', 'false', 'moderate', NULL, NULL, NULL, NULL, NULL, NULL, 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Class: user-supplied respiration data', 'false', 'नासपती', '2–7 months', '60', '210', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (3, 'Peaches', 'आड़ू', NULL, 'fresh_produce', 'fruit', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '2', '90', '95', 'producer', 'false', 'moderate', NULL, NULL, NULL, NULL, NULL, NULL, 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, '5', NULL, '20', NULL, '87', NULL, 'Class: user-supplied respiration data. Rates: USDA Agriculture Handbook 66 (2016), Table 1 — Ripe', 'false', 'पीच', '2–4 weeks', '14', '28', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (4, 'Plums', 'आलूबुखारा', NULL, 'fresh_produce', 'fruit', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '2', '90', '95', 'producer', 'false', 'moderate', NULL, NULL, NULL, NULL, NULL, NULL, 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, '3', NULL, '10', NULL, '20', NULL, 'Class: user-supplied respiration data. Rates: USDA Agriculture Handbook 66 (2016), Table 1 — Ripe', 'false', 'आलुबुखार', '2–5 weeks', '14', '35', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (5, 'Cherries', 'चेरी', NULL, 'fresh_produce', 'fruit', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '2', '90', '95', 'producer', 'false', 'moderate', NULL, NULL, NULL, NULL, NULL, NULL, 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, '8', '22', '28', '46', '65', NULL, 'Class: user-supplied respiration data. Rates: USDA Agriculture Handbook 66 (2016), Table 1 — Sweet cherry', 'false', 'चेरी', '2–3 weeks', '14', '21', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (6, 'Berries', 'बेरी', NULL, 'fresh_produce', 'fruit', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '2', '90', '95', 'producer', 'false', 'high', 'Forced-air cooling', NULL, NULL, NULL, NULL, NULL, 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ESTIMATE: Generic row; strawberry, raspberry and blackberry are all high', 'true', 'बेरी', NULL, NULL, NULL, NULL),
  (7, 'Topped Beets', 'चुकंदर', NULL, 'fresh_produce', 'vegetable', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '2', '90', '95', NULL, 'false', 'low', NULL, NULL, NULL, NULL, NULL, 'Listed in Group 1 (ethylene-producer group) but beets are not themselves an ethylene producer', 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, '5', '11', '18', '31', '60', NULL, 'Class: Kader (2002) Table 1.2 via Watkins & Nock (2012). Rates: USDA Agriculture Handbook 66 (2016), Table 1', 'false', 'बीट', '4 months', '120', '120', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (8, 'Mushrooms', 'मशरूम', NULL, 'fresh_produce', 'vegetable', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '2', '90', '95', NULL, 'false', 'extremely_high', NULL, NULL, NULL, NULL, NULL, 'Listed in Group 1; manual gives no ethylene role for mushrooms', 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, '35', '70', '97', NULL, '264', NULL, 'Class: user-supplied respiration data. Rates: USDA Agriculture Handbook 66 (2016), Table 1', 'false', 'अळंबी', '7–14 days', '7', '14', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (9, 'Asparagus', 'शतावरी', NULL, 'fresh_produce', 'vegetable', '2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '2', '95', '100', 'sensitive', 'false', 'extremely_high', 'Hydrocooling', NULL, NULL, NULL, NULL, NULL, 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, '60', '105', '215', '235', '270', NULL, 'Class: user-supplied respiration data. Rates: USDA Agriculture Handbook 66 (2016), Table 1 — 1 day after harvest', 'false', 'शतावरी', '2–3 weeks', '14', '21', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (10, 'Broccoli', 'ब्रोकली', NULL, 'fresh_produce', 'vegetable', '2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '2', '95', '100', 'sensitive', 'false', 'extremely_high', 'Package icing / liquid ice', NULL, NULL, NULL, NULL, 'Kader lists broccoli as very high (40–60); user data lists it as extremely high', 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, '21', '34', '81', '170', '300', NULL, 'Class: user-supplied respiration data. Rates: USDA Agriculture Handbook 66 (2016), Table 1', 'false', 'ब्रोकोली', '10–14 days', '10', '14', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (11, 'Cabbage', 'पत्ता गोभी', NULL, 'fresh_produce', 'vegetable', '2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '2', '95', '100', 'sensitive', 'false', 'moderate', NULL, NULL, NULL, NULL, NULL, NULL, 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, '5', '11', '18', '28', '42', '62', 'Class: user-supplied respiration data. Rates: USDA Agriculture Handbook 66 (2016), Table 1', 'false', 'कोबी', '3–6 weeks', '21', '42', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (12, 'Carrots', 'गाजर', NULL, 'fresh_produce', 'vegetable', '2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '2', '95', '100', 'sensitive', 'false', 'moderate', NULL, NULL, NULL, NULL, NULL, NULL, 'Produce Cold Storage & Postharvest Handling Technical Manual', '10', '20', '0', '15', '20', '31', '40', '25', NULL, 'Class: user-supplied respiration data. Rates: USDA Agriculture Handbook 66 (2016), Table 1 — Topped carrots', 'false', 'गाजर', '3–6 months', '90', '180', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (13, 'Cauliflower', 'फूलगोभी', NULL, 'fresh_produce', 'vegetable', '2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '2', '95', '100', 'sensitive', 'false', 'high', NULL, NULL, NULL, NULL, NULL, NULL, 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, '17', '21', '34', '46', '79', '92', 'Class: user-supplied respiration data. Rates: USDA Agriculture Handbook 66 (2016), Table 1', 'false', 'फुलकोबी', '3–4 weeks', '21', '28', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (14, 'Celery', 'अजमोद (सेलरी)', NULL, 'fresh_produce', 'vegetable', '2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '2', '95', '100', 'sensitive', 'false', 'low', 'Hydrocooling', NULL, NULL, NULL, NULL, NULL, 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, '15', '20', '31', '40', '71', NULL, 'Class: Kader (2002) Table 1.2 via Watkins & Nock (2012). Rates: USDA Agriculture Handbook 66 (2016), Table 1', 'false', 'सेलरी', '1–2 months', '30', '60', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (15, 'Leafy Greens', 'पत्तेदार साग', NULL, 'fresh_produce', 'vegetable', '2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '2', '95', '100', 'sensitive', 'false', 'very_high', 'Vacuum cooling (head lettuce)', NULL, NULL, NULL, NULL, 'Spinach listed separately as very high respiration', 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ESTIMATE: Generic row; members range from moderate (head lettuce) to extremely high (spinach), very high chosen as a cautious middle', 'true', 'पालेभाज्या', '10–14 days', '10', '14', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (16, 'Radishes', 'मूली', NULL, 'fresh_produce', 'vegetable', '2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '2', '95', '100', 'sensitive', 'false', 'moderate', NULL, NULL, NULL, NULL, NULL, NULL, 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, '16', '20', '34', '74', '130', '172', 'Class: Kader (2002) Table 1.2 via Watkins & Nock (2012) — topped radish; radish with tops is high. Rates: USDA Agriculture Handbook 66 (2016), Table 1 — Topped radish', 'false', 'मुळा', '1–2 months', '30', '60', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (17, 'Dry Garlic', 'लहसुन', NULL, 'fresh_produce', 'vegetable', '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '2', '65', '75', NULL, 'false', 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, '8', '16', '24', '22', '20', NULL, 'Class: user-supplied respiration data. Rates: USDA Agriculture Handbook 66 (2016), Table 1 — Garlic bulbs', 'false', 'लसूण', '6–7 months', '180', '210', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (18, 'Dry Onions', 'प्याज', NULL, 'fresh_produce', 'vegetable', '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '2', '65', '75', NULL, 'false', 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, '3', '5', '7', '7', '8', NULL, 'Class: user-supplied respiration data. Rates: USDA Agriculture Handbook 66 (2016), Table 1 — Onion', 'false', 'कांदा', '1–8 months', '30', '240', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (19, 'Cantaloupes', 'खरबूजा (जालीदार)', NULL, 'fresh_produce', 'fruit', '4', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '4.5', '7', '90', '95', NULL, 'true', 'moderate', NULL, NULL, NULL, NULL, NULL, NULL, 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, '6', '10', '15', '37', '55', '67', 'Class: Kader (2002) Table 1.2 via Watkins & Nock (2012). Rates: USDA Agriculture Handbook 66 (2016), Table 1 — Listed as netted melon', 'false', 'खरबूज (जाळीदार)', '2–3 weeks', '14', '21', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (20, 'Cranberries', 'क्रैनबेरी', NULL, 'fresh_produce', 'fruit', '4', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '4.5', '7', '90', '95', NULL, 'true', 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, '4', '5', '8', NULL, '16', NULL, 'Class: Kader (2002) Table 1.2 via Watkins & Nock (2012). Rates: USDA Agriculture Handbook 66 (2016), Table 1', 'false', 'क्रॅनबेरी', '8–16 weeks', '56', '112', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (21, 'Lemons', 'नींबू', NULL, 'fresh_produce', 'fruit', '4', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '4.5', '7', '90', '95', NULL, 'true', 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, NULL, NULL, '11', '19', '24', NULL, 'ESTIMATE: Citrus; AH-66 rate 11 mg at 10°C implies ~5–8 mg at 5°C. Rates: USDA Agriculture Handbook 66 (2016), Table 1', 'true', 'लिंबू', '1–6 months', '30', '180', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (22, 'Limes', 'नींबू (कागज़ी)', NULL, 'fresh_produce', 'fruit', '4', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '4.5', '7', '90', '95', NULL, 'true', 'low', NULL, NULL, NULL, NULL, NULL, 'USDA AH-66: respiration <10 mg CO2/kg·h at 10°C; no class assigned', 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ESTIMATE: Citrus; AH-66 rate <10 mg at 10°C', 'true', 'लिंबू (कागदी)', '6–8 weeks', '42', '56', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (23, 'Oranges', 'संतरा', NULL, 'fresh_produce', 'fruit', '4', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '4.5', '7', '90', '95', NULL, 'true', 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, '4', '6', '8', '18', '28', NULL, 'Class derived from USDA AH-66 rate at 5°C (6 mg) using Kader thresholds. Rates: USDA Agriculture Handbook 66 (2016), Table 1', 'false', 'संत्री', '3–8 weeks', '21', '56', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (24, 'Tangerines', 'किन्नू / मौसमी', NULL, 'fresh_produce', 'fruit', '4', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '4.5', '7', '90', '95', NULL, 'true', 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, NULL, '6', '8', '16', '25', NULL, 'Class derived from USDA AH-66 rate at 5°C (6 mg) using Kader thresholds. Rates: USDA Agriculture Handbook 66 (2016), Table 1 — Listed as mandarin (tangerine)', 'false', 'मोसंबी / किनू', '2–4 weeks', '14', '28', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (25, 'Yucca Root', 'टैपिओका (कसावा)', NULL, 'fresh_produce', 'vegetable', '4', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '4.5', '7', '90', '95', NULL, 'true', 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '40', 'ESTIMATE: AH-66 rate 40 mg at 25°C, scaled to 5°C assuming Q10≈2–3 (~5–10 mg). Rates: USDA Agriculture Handbook 66 (2016), Table 1 — Listed as cassava', 'true', 'साबुदाणा कंद (कसावा)', '1–2 months', '30', '60', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (26, 'Cucumbers', 'खीरा', NULL, 'fresh_produce', 'vegetable', '5', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '10', '10', '85', '90', 'sensitive', 'true', 'moderate', NULL, NULL, NULL, NULL, NULL, NULL, 'Produce Cold Storage & Postharvest Handling Technical Manual', '10', '15', '10', NULL, NULL, '26', '29', '31', '37', 'Class: user-supplied respiration data. Rates: USDA Agriculture Handbook 66 (2016), Table 1', 'false', 'काकडी', '10–14 days', '10', '14', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (27, 'Eggplants', 'बैंगन', NULL, 'fresh_produce', 'vegetable', '5', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '10', '10', '85', '90', 'sensitive', 'true', 'high', NULL, NULL, NULL, NULL, NULL, NULL, 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ESTIMATE: AH-66 rate 69 mg at 12.5°C, scaled to 5°C assuming Q10≈2–3 (~30–40 mg)', 'true', 'वांगी', '1–2 weeks', '7', '14', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (28, 'Okra', 'भिंडी', NULL, 'fresh_produce', 'vegetable', '5', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '10', '10', '85', '90', 'sensitive', 'true', 'very_high', NULL, NULL, NULL, NULL, NULL, NULL, 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, NULL, '40', '91', '146', '261', '345', 'Class: Kader (2002) Table 1.2 via Watkins & Nock (2012). Rates: USDA Agriculture Handbook 66 (2016), Table 1', 'false', 'भेंडी', '7–10 days', '7', '10', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (29, 'Sweet Peppers', 'शिमला मिर्च', NULL, 'fresh_produce', 'vegetable', '5', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '10', '10', '85', '90', 'sensitive', 'true', 'moderate', 'Forced-air cooling', NULL, NULL, NULL, NULL, NULL, 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, NULL, '7', '12', '27', '34', NULL, 'Class: user-supplied respiration data. Rates: USDA Agriculture Handbook 66 (2016), Table 1 — Pepper', 'false', 'ढोबळी मिरची', '2–3 weeks', '14', '21', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (30, 'Storage Potatoes', 'आलू', NULL, 'fresh_produce', 'vegetable', '5', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '10', '10', '85', '90', 'sensitive', 'true', 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, NULL, '12', '16', '17', '22', NULL, 'Class: user-supplied respiration data. Rates: USDA Agriculture Handbook 66 (2016), Table 1 — Cured potato', 'false', 'बटाटा', '5–10 months', '150', '300', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (31, 'Summer Squash', 'तोरी / कद्दू', NULL, 'fresh_produce', 'vegetable', '5', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '10', '10', '85', '90', 'sensitive', 'true', 'moderate', NULL, NULL, NULL, NULL, NULL, 'AH-66 rate at 5°C (32 mg) would be "high"; Kader lists summer squash as moderate', 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, '25', '32', '67', '153', '164', NULL, 'Class: Kader (2002) Table 1.2 via Watkins & Nock (2012). Rates: USDA Agriculture Handbook 66 (2016), Table 1', 'false', 'दुधी / भोपळा', '1–2 weeks', '7', '14', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (32, 'Avocados', 'एवोकाडो', NULL, 'fresh_produce', 'fruit', '6', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '13', '15', '85', '90', 'producer', 'true', 'high', NULL, NULL, NULL, NULL, NULL, NULL, 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, NULL, '35', '105', NULL, '190', NULL, 'Class derived from USDA AH-66 rate at 5°C (35 mg) using Kader thresholds. Rates: USDA Agriculture Handbook 66 (2016), Table 1', 'false', 'अ‍ॅव्होकॅडो', '2–4 weeks', '14', '28', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (33, 'Bananas', 'केला', NULL, 'fresh_produce', 'fruit', '6', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '13', '15', '85', '90', 'producer', 'true', 'moderate', NULL, NULL, NULL, NULL, NULL, NULL, 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, NULL, NULL, '80', NULL, '280', NULL, 'Class: Kader (2002) Table 1.2 via Watkins & Nock (2012). Rates: USDA Agriculture Handbook 66 (2016), Table 1 — Ripe bananas', 'false', 'केळी', '1–4 weeks', '7', '28', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (34, 'Grapefruit', 'चकोतरा', NULL, 'fresh_produce', 'fruit', '6', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '13', '15', '85', '90', 'producer', 'true', 'low', NULL, NULL, NULL, NULL, NULL, 'USDA AH-66: respiration <10 mg CO2/kg·h at 15°C; no class assigned', 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ESTIMATE: Citrus; AH-66 rate <10 mg even at 15°C', 'true', 'पपनस', '6–8 weeks', '42', '56', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (35, 'Guava', 'अमरूद', NULL, 'fresh_produce', 'fruit', '6', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '13', '15', '85', '90', 'producer', 'true', 'moderate', NULL, NULL, NULL, NULL, NULL, NULL, 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, NULL, NULL, '34', NULL, '74', NULL, 'ESTIMATE: AH-66 rate 34 mg at 10°C, scaled to 5°C assuming Q10≈2 (~17 mg). Rates: USDA Agriculture Handbook 66 (2016), Table 1', 'true', 'पेरू', '2–3 weeks', '14', '21', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (36, 'Mangoes', 'आम', NULL, 'fresh_produce', 'fruit', '6', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '13', '15', '85', '90', 'producer', 'true', 'moderate', NULL, NULL, NULL, NULL, NULL, NULL, 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, NULL, '16', '35', '58', '113', NULL, 'Class derived from USDA AH-66 rate at 5°C (16 mg) using Kader thresholds; mango is chilling-sensitive and not stored at 5°C. Rates: USDA Agriculture Handbook 66 (2016), Table 1', 'false', 'आंबा', '2–3 weeks', '14', '21', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (37, 'Melons', 'खरबूजा', NULL, 'fresh_produce', 'fruit', '6', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '13', '15', '85', '90', 'producer', 'true', 'moderate', NULL, NULL, NULL, NULL, NULL, 'Honeydew is low and cantaloupe moderate (Kader); generic Melons row left unclassified', 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ESTIMATE: Generic row; honeydew is low and cantaloupe moderate, moderate chosen as the more cautious value', 'true', 'खरबूज', '3–4 weeks', '21', '28', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (38, 'Papayas', 'पपीता', NULL, 'fresh_produce', 'fruit', '6', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '13', '15', '85', '90', 'producer', 'true', 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, NULL, '5', NULL, '19', '80', NULL, 'Class: Kader (2002) Table 1.2 via Watkins & Nock (2012). Rates: USDA Agriculture Handbook 66 (2016), Table 1 — Ripe', 'false', 'पपई', '1–3 weeks', '7', '21', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (39, 'Ripe Tomatoes', 'टमाटर (पका)', NULL, 'fresh_produce', 'vegetable', '6', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '13', '15', '85', '90', 'producer', 'true', 'moderate', NULL, NULL, NULL, NULL, NULL, NULL, 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, NULL, NULL, '15', '22', '35', '43', 'Class: user-supplied respiration data. Rates: USDA Agriculture Handbook 66 (2016), Table 1 — Listed as tomato', 'false', 'टोमॅटो (पिकलेला)', '1–3 weeks', '7', '21', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (40, 'Ginger', 'अदरक', NULL, 'fresh_produce', 'vegetable', '7', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '18', '21', '85', '90', NULL, 'true', 'moderate', NULL, NULL, NULL, NULL, NULL, NULL, 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '63', NULL, 'ESTIMATE: AH-66 rate 63 mg at 20°C, scaled to 5°C assuming Q10≈2–3 (~13–22 mg). Rates: USDA Agriculture Handbook 66 (2016), Table 1', 'true', 'आले', '6 months', '180', '180', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (41, 'Jicama', 'शंकालु', NULL, 'fresh_produce', 'vegetable', '7', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '18', '21', '85', '90', NULL, 'true', 'moderate', NULL, NULL, NULL, NULL, NULL, NULL, 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, '6', '11', '14', NULL, '6', NULL, 'Class derived from USDA AH-66 rate at 5°C (11 mg) using Kader thresholds. Rates: USDA Agriculture Handbook 66 (2016), Table 1', 'false', 'शंकालू', '1–2 months', '30', '60', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (42, 'Sweet Potatoes', 'शकरकंद', NULL, 'fresh_produce', 'vegetable', '7', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '18', '21', '85', '90', NULL, 'true', 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Class: user-supplied respiration data', 'false', 'रताळे', '4–7 months', '120', '210', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (43, 'Watermelon', 'तरबूज', NULL, 'fresh_produce', 'fruit', '7', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '18', '21', '85', '90', NULL, 'true', 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, NULL, '4', '8', NULL, '21', NULL, 'Class: Kader (2002) Table 1.2 via Watkins & Nock (2012). Rates: USDA Agriculture Handbook 66 (2016), Table 1', 'false', 'कलिंगड', '2–3 weeks', '14', '21', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (44, 'Yams', 'रतालू', NULL, 'fresh_produce', 'vegetable', '7', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '18', '21', '85', '90', NULL, 'true', 'low', NULL, NULL, NULL, NULL, NULL, NULL, 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ESTIMATE: No data; assumed similar to sweet potato (low), a comparable storage root', 'true', 'कणगर', '2–7 months', '60', '210', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (45, 'Mature Green Tomatoes', 'टमाटर (हरा)', NULL, 'fresh_produce', 'vegetable', '7', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '18', '21', '85', '90', NULL, 'true', 'moderate', NULL, NULL, NULL, NULL, NULL, NULL, 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, NULL, NULL, '15', '22', '35', '43', 'Class: user-supplied respiration data. Rates: USDA Agriculture Handbook 66 (2016), Table 1 — Listed as tomato (maturity not specified)', 'false', 'टोमॅटो (हिरवा)', '2–5 weeks', '14', '35', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (46, 'Sweet Corn', 'मीठी मकई', NULL, 'fresh_produce', 'vegetable', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'extremely_high', 'Hydrocooling', NULL, NULL, NULL, NULL, 'Not in storage group table', 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, '41', '63', '105', '159', '261', '359', 'Class: user-supplied respiration data. Rates: USDA Agriculture Handbook 66 (2016), Table 1', 'false', 'स्वीट कॉर्न', '5–8 days', '5', '8', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (47, 'Spinach', 'पालक', NULL, 'fresh_produce', 'vegetable', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'extremely_high', NULL, NULL, NULL, NULL, NULL, 'Not in storage group table; likely falls under Leafy Greens (Group 2)', 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, '21', '45', '110', '179', '230', NULL, 'Class: user-supplied respiration data. Rates: USDA Agriculture Handbook 66 (2016), Table 1', 'false', 'पालक', '10–14 days', '10', '14', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (48, 'Whole Milk Powder', 'फुल क्रीम दूध पाउडर', NULL, 'dairy', 'powder', NULL, '2.0', '4.0', '26.0', NULL, '6.5', '6.7', NULL, NULL, NULL, NULL, NULL, '25', NULL, '65', NULL, NULL, NULL, NULL, 'Amorphous lactose caking and lipid autoxidation', 'Nitrogen-flushed or vacuum-sealed light-barrier bags', '<25°C, <65% RH, N2-flushed barrier bags', '12–24 months with N2 flush/vacuum and light barrier', 'pH is for reconstituted milk', 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'false', 'पूर्ण दूध पावडर', NULL, NULL, NULL, NULL),
  (49, 'Skim Milk Powder', 'स्किम दूध पाउडर', NULL, 'dairy', 'powder', NULL, '3.0', '4.5', NULL, '1.5', '6.5', '6.8', NULL, NULL, NULL, NULL, NULL, '25', NULL, '65', NULL, NULL, NULL, NULL, 'Lactose crystallization and Maillard browning', 'Multi-ply paper bag with PE liner', '<25°C, <65% RH, multi-ply paper/PE liner', NULL, 'pH is for reconstituted milk', 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'false', 'स्किम दूध पावडर', NULL, NULL, NULL, NULL),
  (50, 'Cheddar Cheese', 'चेडर चीज़', NULL, 'dairy', 'cheese', NULL, '36.0', '39.0', '30.0', '34.0', '5.10', '5.35', NULL, NULL, NULL, NULL, '0', '5.5', '80', '85', NULL, NULL, NULL, NULL, 'Pathogen growth, surface mold, lipolytic rancidity', 'Vacuum shrink-wrap', '0–5.5°C, 80–85% RH, vacuum shrink-wrap', NULL, NULL, 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'false', 'चेडर चीज', NULL, NULL, NULL, NULL),
  (51, 'Plain Yogurt', 'दही', NULL, 'dairy', 'cultured', NULL, '85.0', '88.0', '3.25', '4.0', '3.80', '4.65', NULL, NULL, NULL, NULL, '0', '4', NULL, NULL, NULL, NULL, NULL, NULL, 'Post-acidification and syneresis (whey separation)', 'Sealed PP cups with foil lids', '0–4°C, sealed PP cups with foil lids', NULL, NULL, 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'false', 'दही', NULL, NULL, NULL, NULL),
  (52, 'Salted Butter', 'नमकीन मक्खन', NULL, 'dairy', 'fat', NULL, '15.5', '16.5', '80.0', '82.0', '6.1', '6.4', NULL, NULL, NULL, NULL, '0', '4', NULL, '75', NULL, NULL, NULL, NULL, 'Hydrolytic lipolysis and light-induced oxidation', 'Foil laminate wrapper', '0–4°C, foil laminate wrapper, <75% RH', NULL, NULL, 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'false', 'खारट लोणी', NULL, NULL, NULL, NULL),
  (53, 'Potato Crisps', 'आलू चिप्स', NULL, 'bakery_snack', 'snack', NULL, '1.2', '2.5', '30.0', '38.0', NULL, NULL, '0.15', '0.25', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Loss of crispness (aw > 0.35) and oxidation', 'N2-flushed aluminium foil pouch (high barrier: low WVTR and low OTR)', NULL, NULL, 'Manual table says "High WVTR & OTR"; interpreted as high barrier (low WVTR/OTR). Text elsewhere gives fat as 25–38%.', 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'false', 'बटाटा वेफर्स', NULL, NULL, NULL, NULL),
  (54, 'Puffed Corn Snacks', 'मकई के कुरकुरे', NULL, 'bakery_snack', 'snack', NULL, '1.5', '3.0', '22.0', '32.0', NULL, NULL, '0.18', '0.28', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Textural softening and rancidity', 'High-barrier foil flow-pack under MAP', NULL, NULL, NULL, 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'false', 'मक्याचे कुरकुरे', NULL, NULL, NULL, NULL),
  (55, 'Wheat Crackers', 'गेहूं के क्रैकर्स', NULL, 'bakery_snack', 'bakery', NULL, '2.0', '4.0', '8.0', '20.0', NULL, NULL, '0.20', '0.30', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Starch matrix rubberiness and hexanal off-flavor', 'Waxed inner wrap in paperboard/foil laminate', NULL, NULL, NULL, 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'false', 'गव्हाचे क्रॅकर्स', NULL, NULL, NULL, NULL),
  (56, 'Soft Cookies', 'नरम बिस्कुट', NULL, 'bakery_snack', 'bakery', NULL, '8.0', '12.0', '10.0', '18.0', NULL, NULL, '0.60', '0.75', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Staling, mold growth, moisture loss', 'Hermetic moisture-retentive polymer film', NULL, NULL, NULL, 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'false', 'मऊ बिस्किटे', NULL, NULL, NULL, NULL),
  (57, 'Fresh Bread / Cakes', 'ब्रेड / केक', NULL, 'bakery_snack', 'bakery', NULL, '35.0', '45.0', '2.0', '8.0', NULL, NULL, '0.88', '0.95', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Mold growth (Penicillium) and staling', 'Polyethylene bags with preservatives / MAP', NULL, NULL, NULL, 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'false', 'ब्रेड / केक', NULL, NULL, NULL, NULL),
  (58, 'Cabbage Kimchi', 'किमची', NULL, 'fermented', 'fermented_vegetable', NULL, NULL, NULL, NULL, NULL, '3.8', '4.2', NULL, NULL, '1.5', '4.0', '-1', '4', NULL, NULL, NULL, NULL, NULL, NULL, 'Over-acidification (>0.9% acid), softening, gas pressure', 'Gas-vented containers', '-1 to 4°C, gas-vented containers', '3–12 months', 'pH range is optimal target', 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'false', 'किमची', NULL, NULL, NULL, NULL),
  (59, 'Sauerkraut', 'खट्टी पत्ता गोभी', NULL, 'fermented', 'fermented_vegetable', NULL, NULL, NULL, NULL, NULL, '3.3', '3.8', NULL, NULL, '2.0', '2.5', '0', '4', NULL, NULL, NULL, NULL, NULL, NULL, 'Kahm yeast film, softening, putrid odor if not submerged', 'Kept submerged in brine under weight', '0–4°C, submerged in brine under weight', '6+ months', NULL, 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'false', 'आंबवलेली कोबी', NULL, NULL, NULL, NULL),
  (60, 'Fermented Dill Pickles', 'खमीरी खीरा अचार', NULL, 'fermented', 'fermented_vegetable', NULL, NULL, NULL, NULL, NULL, '3.4', '3.8', NULL, NULL, '3.0', '5.0', '1', '4', NULL, NULL, NULL, NULL, NULL, NULL, 'Hollow pickles, softening (pectin loss), bloater damage', 'Chilled, or hot-filled pasteurized glass', '1–4°C, or hot-filled pasteurized glass', NULL, NULL, 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'false', 'आंबवलेले काकडी लोणचे', NULL, NULL, NULL, NULL),
  (61, 'Pickled Jalapeños', 'हालापेन्यो अचार', NULL, 'fermented', 'acidified_vegetable', NULL, NULL, NULL, NULL, NULL, '3.1', '3.6', NULL, NULL, NULL, NULL, '15', '25', NULL, NULL, NULL, NULL, NULL, NULL, 'Softening, loss of pungency, ring clouding', 'Hot-filled and sealed', 'Ambient (15–25°C) if hot-filled and sealed', NULL, 'Acidified with vinegar + salt; salt % not given', 'Produce Cold Storage & Postharvest Handling Technical Manual', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'false', 'हालापेन्यो लोणचे', NULL, NULL, NULL, NULL),
  (62, 'Grapes', 'अंगूर', NULL, 'fresh_produce', 'fruit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'low', NULL, NULL, NULL, NULL, NULL, 'Storage group not given', 'Respiration rates data (user-supplied)', NULL, NULL, NULL, '3', '7', '13', NULL, '27', NULL, 'Class: user-supplied respiration data. Rates: USDA Agriculture Handbook 66 (2016), Table 1 — Table grape', 'false', 'द्राक्षे', '1–6 months', '30', '180', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (63, 'Apricots', 'खुबानी', NULL, 'fresh_produce', 'fruit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'moderate', NULL, NULL, NULL, NULL, NULL, 'Storage group not given', 'Respiration rates data (user-supplied)', NULL, NULL, NULL, '6', NULL, '16', NULL, '40', NULL, 'Class: user-supplied respiration data. Rates: USDA Agriculture Handbook 66 (2016), Table 1', 'false', 'जर्दाळू', '1–3 weeks', '7', '21', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (64, 'Nectarines', 'शफ़तालू', NULL, 'fresh_produce', 'fruit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'moderate', NULL, NULL, NULL, NULL, NULL, 'Storage group not given', 'Respiration rates data (user-supplied)', NULL, NULL, NULL, '5', NULL, '20', NULL, '87', NULL, 'Class: user-supplied respiration data. Rates: USDA Agriculture Handbook 66 (2016), Table 1 — Ripe', 'false', 'नेक्टरिन', '2–4 weeks', '14', '28', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (65, 'Lettuce', 'सलाद पत्ता', NULL, 'fresh_produce', 'vegetable', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'moderate', NULL, NULL, NULL, NULL, NULL, 'Storage group not given; manual lists head lettuce under Leafy Greens (Group 2)', 'Respiration rates data (user-supplied)', NULL, NULL, NULL, '12', '17', '31', '39', '56', '82', 'Class: user-supplied respiration data. Rates: USDA Agriculture Handbook 66 (2016), Table 1 — Head lettuce', 'false', 'लेट्यूस', '2–3 weeks', '14', '21', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (66, 'Immature Potatoes', 'नया आलू', NULL, 'fresh_produce', 'vegetable', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'moderate', NULL, NULL, NULL, NULL, NULL, 'Storage group not given', 'Respiration rates data (user-supplied)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Class: user-supplied respiration data', 'false', 'नवे बटाटे', '10–14 days', '10', '14', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (67, 'Strawberries', 'स्ट्रॉबेरी', NULL, 'fresh_produce', 'fruit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'high', NULL, NULL, NULL, NULL, NULL, 'Storage group not given; manual groups berries in Group 1', 'Respiration rates data (user-supplied)', '25', '50', '0', '16', NULL, '75', NULL, '150', NULL, 'Class: user-supplied respiration data. Rates: USDA Agriculture Handbook 66 (2016), Table 1', 'false', 'स्ट्रॉबेरी', '7–10 days', '7', '10', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (68, 'Blackberries', 'ब्लैकबेरी', NULL, 'fresh_produce', 'fruit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'high', NULL, NULL, NULL, NULL, NULL, 'Storage group not given; manual groups berries in Group 1', 'Respiration rates data (user-supplied)', NULL, NULL, NULL, '19', '36', '62', '75', '115', NULL, 'Class: user-supplied respiration data. Rates: USDA Agriculture Handbook 66 (2016), Table 1', 'false', 'ब्लॅकबेरी', '3–6 days', '3', '6', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (69, 'Raspberries', 'रसभरी', NULL, 'fresh_produce', 'fruit', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'high', NULL, NULL, NULL, NULL, NULL, 'Storage group not given; manual groups berries in Group 1', 'Respiration rates data (user-supplied)', NULL, NULL, NULL, NULL, '23', '35', '42', '125', NULL, 'Class: user-supplied respiration data. Rates: USDA Agriculture Handbook 66 (2016), Table 1', 'false', 'रास्पबेरी', '3–6 days', '3', '6', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (70, 'Lima Beans', 'लोबिया (लीमा बीन्स)', NULL, 'fresh_produce', 'vegetable', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'high', NULL, NULL, NULL, NULL, NULL, 'Storage group not given', 'Respiration rates data (user-supplied)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Class: user-supplied respiration data', 'false', 'लीमा बीन्स', '5–7 days', '5', '7', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (71, 'Artichokes', 'आर्टिचोक', NULL, 'fresh_produce', 'vegetable', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'very_high', NULL, NULL, NULL, NULL, NULL, 'Storage group not given', 'Respiration rates data (user-supplied)', NULL, NULL, NULL, '30', '43', '71', '110', '193', NULL, 'Class: user-supplied respiration data. Rates: USDA Agriculture Handbook 66 (2016), Table 1', 'false', 'आर्टिचोक', '2–3 weeks', '14', '21', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (72, 'Snap Beans', 'फ्रेंच बीन्स', NULL, 'fresh_produce', 'vegetable', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'very_high', 'Forced-air cooling', NULL, NULL, NULL, NULL, 'Storage group not given; manual recommends forced-air cooling', 'Respiration rates data (user-supplied)', NULL, NULL, NULL, '20', '34', '58', '92', '130', NULL, 'Class: user-supplied respiration data. Rates: USDA Agriculture Handbook 66 (2016), Table 1', 'false', 'फरसबी', '7–10 days', '7', '10', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (73, 'Green Onions', 'हरा प्याज', NULL, 'fresh_produce', 'vegetable', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'very_high', 'Package icing / liquid ice', NULL, NULL, NULL, NULL, 'Storage group not given; manual recommends package icing', 'Respiration rates data (user-supplied)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Class: user-supplied respiration data', 'false', 'कांद्याची पात', '3 weeks', '21', '21', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (74, 'Brussels Sprouts', 'ब्रसेल्स स्प्राउट्स', NULL, 'fresh_produce', 'vegetable', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'very_high', NULL, NULL, NULL, NULL, NULL, 'Storage group not given', 'Respiration rates data (user-supplied)', NULL, NULL, NULL, '40', '70', '147', '200', '276', NULL, 'Class: user-supplied respiration data. Rates: USDA Agriculture Handbook 66 (2016), Table 1', 'false', 'ब्रसेल्स स्प्राउट्स', '3–5 weeks', '21', '35', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (75, 'Cilantro', 'हरा धनिया', NULL, 'fresh_produce', 'vegetable', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'very_high', NULL, NULL, NULL, NULL, NULL, 'Source also gives 47 mL CO2/kg·h at 10°C. Note: 13 at 0°C falls in the moderate range numerically, though source classes it very high', 'Respiration rates data (user-supplied)', '13', '13', '0', '22', '30', NULL, NULL, NULL, NULL, 'Class: user-supplied respiration data. Rates: USDA Agriculture Handbook 66 (2016), Table 1 — Listed as coriander', 'false', 'कोथिंबीर', '2 weeks', '14', '14', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (76, 'Green Peas', 'मटर', NULL, 'fresh_produce', 'vegetable', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'extremely_high', NULL, NULL, NULL, NULL, NULL, 'Storage group not given', 'Respiration rates data (user-supplied)', NULL, NULL, NULL, '38', '64', '86', '175', '271', '313', 'Class: user-supplied respiration data. Rates: USDA Agriculture Handbook 66 (2016), Table 1 — Garden pea', 'false', 'वाटाणा', '1–2 weeks', '7', '14', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (77, 'Nuts', 'मेवे', NULL, 'dried_produce', 'dried', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'very_low', NULL, NULL, NULL, NULL, NULL, 'Storage conditions not given', 'Respiration rates data (user-supplied)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Class: user-supplied respiration data', 'false', 'सुका मेवा', NULL, NULL, NULL, NULL),
  (78, 'Dates', 'खजूर', NULL, 'dried_produce', 'dried', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'very_low', NULL, NULL, NULL, NULL, NULL, 'Storage conditions not given', 'Respiration rates data (user-supplied)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Class: user-supplied respiration data', 'false', 'खजूर', '6–12 months', '180', '360', 'Cantwell, M. (2001), UC Davis — approximate storage life at recommended temperature and humidity'),
  (79, 'Dried Fruits', 'सूखे फल', NULL, 'dried_produce', 'dried', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'very_low', NULL, NULL, NULL, NULL, NULL, 'Storage conditions not given', 'Respiration rates data (user-supplied)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Class: user-supplied respiration data', 'false', 'सुकी फळे', NULL, NULL, NULL, NULL),
  (80, 'Dried Vegetables', 'सूखी सब्ज़ियाँ', NULL, 'dried_produce', 'dried', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'very_low', NULL, NULL, NULL, NULL, NULL, 'Storage conditions not given', 'Respiration rates data (user-supplied)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Class: user-supplied respiration data', 'false', 'सुक्या भाज्या', NULL, NULL, NULL, NULL)
on conflict (id) do nothing;

-- keep the id sequence ahead of the seeded rows
select setval(pg_get_serial_sequence('public.products', 'id'), greatest((select max(id) from public.products), 1));
